apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${{values.component_id}}
resources:
- ../../base
helmCharts:
{%- if values.kubernetes.enabled %}
- name: devxp-app
  releaseName: devxp-app
  version: 0.1.62
  repo: https://devxp-tech.github.io/helm-charts
  valuesInline:
    name: ${{values.component_id}}
    image:
      repository: ghcr.io/devxp-tech/${{values.component_id}}
      tag: latest
    autoscaling:
      enabled: ${{ values.kubernetes.autoscaling.enabled }}
      minReplicas: ${{ values.kubernetes.autoscaling.minReplicas }}
      maxReplicas: ${{ values.kubernetes.autoscaling.maxReplicas }}
      targetCPUUtilizationPercentage: ${{ values.kubernetes.autoscaling.targetCPUUtilizationPercentage }}
    resources:
      requests:
        memory: ${{ values.kubernetes.resources.requests.memory }}
        cpu: ${{ values.kubernetes.resources.requests.cpu }}
      limits:
        memory: ${{ values.kubernetes.resources.limits.memory }}
        cpu: ${{ values.kubernetes.resources.limits.cpu }}
    network:
      enabled: ${{ values.kubernetes.network.enabled }}
      domain: ${{ values.kubernetes.network.domain }}
      service:
        type: ${{ values.kubernetes.network.type }}
        port: ${{ values.kubernetes.network.port }}
    probe:
      enabled: ${{ values.kubernetes.probe.enabled }}
      livenessProbe:
        path: ${{ values.kubernetes.probe.livenessProbe.path }}
        port: ${{ values.kubernetes.probe.livenessProbe.port }}
      readinessProbe:
        path: ${{ values.kubernetes.probe.readinessProbe.path }}
        port: ${{ values.kubernetes.probe.readinessProbe.port }}
    deploy:
      enabled: ${{ values.kubernetes.probe.enabled }}
    sa:
      enabled: ${{ values.kubernetes.sa.enabled }}
    quota:
      enabled: ${{ values.kubernetes.quota.enabled }}
      requests:
        memory: ${{ values.kubernetes.quota.requests.memory }}
        cpu: ${{ values.kubernetes.quota.requests.cpu }}
      limits:
        memory: ${{ values.kubernetes.quota.limits.memory }}
        cpu: ${{ values.kubernetes.quota.limits.cpu }}
{%- endif %}

{%- if values.infra.enabled %}
- name: devxp-infra
  releaseName: devxp-infra
  version: 0.0.3
  repo: https://devxp-tech.github.io/helm-charts
  valuesInline:
    name: ${{values.component_id}}
  {%- if values.infra.Bucket.enabled %}
    Bucket:
      enabled: true
  {%- endif %}
  {%- if values.infra.RDSInstance.enabled %}
    RDSInstance:
      enabled: true
  {%- endif %}
{%- endif %}